spring.application.name=employeemanagement
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/employeemanagement?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:Vishal@123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
